Repository Dongle-market/Dongle-FE, pull requests merged in 2024-11, with the labels that each got.

#32 [feat] 마이동글: 반려동물 추가 레이아웃(입국신고서)
  public/images/cat.png
  public/images/puppy.png
  public/svgs/element/error.svg
  src/components/items/CartItem.tsx
  src/components/navbar/MyDongleFooterNav.tsx
  src/pages/mydongle/add.tsx
  src/pages/mymarket/cart.tsx
Labels: feat

#35 [feat] 마이마켓 주문내역 날짜별 조회
  public/svgs/element/rocket.svg
  src/components/items/HistoryItem.tsx
  src/pages/mymarket/history.tsx
Labels: feat

#38 [feat] 유저 페이지 레이아웃 구현
  public/images/babodaejang.png
  public/svgs/element/badge.svg
  public/svgs/element/calendar.svg
  public/svgs/element/kakaotalk.svg
  public/svgs/pet/petsportcode.svg
  src/components/items/LogoutModal.tsx
  src/components/items/PetsPort.tsx
  src/components/navbar/MainFooterNav.tsx
  src/components/navbar/MyDongleFooterNav.tsx
  src/components/navbar/MyMarketFooterNav.tsx
  src/components/navbar/UserInfoFooterNav.tsx
  src/pages/myDongle/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
Labels: feat

#40 [feat] 마이동글: 입국신고서 컴포넌트 수정
  public/images/cat.png
  public/images/puppy.png
  public/svgs/pet/addpetactive.svg
  src/components/myDongle/myDongleHeader.tsx
  src/pages/mydongle/add.tsx
Labels: feat

#43 [feat] 마이마켓: 텅 비었을때
  public/svgs/element/empty_cart.svg
  public/svgs/element/empty_heart.svg
  public/svgs/element/empty_order.svg
  src/components/header/SelectBox.tsx
  src/pages/index.tsx
  src/pages/mymarket/cart.tsx
  src/pages/mymarket/history.tsx
  src/pages/mymarket/wishlist.tsx
Labels: feat

#45 [feat] 마이마켓: 펫선택 수정
  src/components/items/CategoryItem.tsx
  src/components/items/HistoryItem.tsx
  src/components/items/SelectPets.tsx
  src/pages/mymarket/history.tsx
  src/pages/mymarket/wishlist.tsx
Labels: feat

#47 [feat] 카테고리&아이템: 디테일 수정
  src/components/header/CategoryDetailHeader.tsx
  src/components/header/ItemHeader.tsx
  src/components/items/MainItem.tsx
  src/components/navbar/ItemFooter.tsx
  src/pages/category/food.tsx
  src/pages/category/goods.tsx
  src/pages/category/index.tsx
  src/pages/category/snack.tsx
  src/pages/item/index.tsx
Labels: feat

#50 [feat] 마이동글: 입국신고서 펫 프로필사진 선택 추가
  public/images/CatEmoji.png
  public/images/DogEmoji.png
  public/images/RabbitEmoji.png
  public/images/petprofileimages/cat1.png
  public/images/petprofileimages/cat2.png
  public/images/petprofileimages/cat3.png
  public/images/petprofileimages/dog1.png
  public/images/petprofileimages/dog2.png
  public/images/petprofileimages/dog3.png
  public/images/selectpets/CatEmoji.png
  public/images/selectpets/DogEmoji.png
  public/images/selectpets/MouseEmoji.png
  src/components/items/SelectPets.tsx
  src/components/myDongle/myDongleHeader.tsx
  src/pages/mydongle/add.tsx
Labels: feat

#49 [feat] 카테고리별 상품리스트 api 부착
  src/components/items/CategoryItem.tsx
  src/components/items/CategoryItemsRow.tsx
  src/pages/category/food.tsx
  src/pages/category/index.tsx
  src/services/api/categoryAPI.ts
  src/utils/removeHtmlTags.ts
Labels: feat

#53 [fix] 마이마켓: api연결 후 오류 수정
  package-lock.json
  package.json
  src/components/header/CategoryDetailHeader.tsx
  src/components/header/CategoryHeader.tsx
  src/components/header/ItemHeader.tsx
  src/components/header/MainHeader.tsx
  src/components/header/MyDongleHeader.tsx
  src/components/header/PaymentsHeader.tsx
  src/pages/myDongle/index.tsx
  src/pages/mydongle/add.tsx
  src/pages/mymarket/wishlist.tsx
  src/utils/removeHtmlTags.ts
Labels: fix

#56 [feat] PG결제 구현
  package-lock.json
  package.json
  public/svgs/element/x_small.svg
  src/components/items/CartItem.tsx
  src/components/items/OrderSummary.tsx
  src/components/payments/OrderItem.tsx
  src/components/payments/TossPayButton.tsx
  src/components/payments/UserContactInfo.tsx
  src/pages/mymarket/cart.tsx
  src/pages/payments/fail.tsx
  src/pages/payments/index.tsx
  src/pages/payments/success.tsx
  src/services/payments/payments.ts
  src/services/payments/payments.type.ts
  src/services/payments/toss.ts
  src/services/users/users.ts
  src/services/users/users.type.ts
  src/types/item.ts
Labels: feat, refactor

#57 [feat] 마이동글: 반려동물 조회 수정
  public/svgs/pet/codeBlock.svg
  public/svgs/pet/passportcode.svg
  public/svgs/pet/petsportcode.svg
  src/components/items/HistoryItem.tsx
  src/components/items/MyDongleHistoryItem.tsx
  src/components/items/PassPort.tsx
  src/components/items/PetsPort.tsx
  src/pages/myDongle/index.tsx
  src/pages/profile/index.tsx
  src/services/axios.setting.ts
  src/styles/globals.css
Labels: feat

#58 [feat] 마이동글 반려동물 API 추가
  src/pages/mydongle/add.tsx
  src/services/pets/pets.ts
  src/services/pets/pets.type.ts
Labels: feat

#59 [feat] 메인페이지 API 부착
  public/svgs/logo/logo_cat.svg
  src/components/header/MainHeader.tsx
  src/components/header/MenuBar.tsx
  src/components/header/Toggle.tsx
  src/components/items/MainItem.tsx
  src/components/login/LoginComponent.tsx
  src/components/login/SplashComponent.tsx
  src/pages/category/food.tsx
  src/pages/category/index.tsx
  src/pages/home/index.tsx
  src/services/api/itemAPI.ts
Labels: feat

#64 [feat] 페이지 UI 디테일 수정
  public/svgs/element/x_xsmall.svg
  src/components/items/HistoryItem.tsx
  src/components/items/OrderCancelModal.tsx
  src/components/items/PetsPort.tsx
  src/components/payments/OrderItem.tsx
  src/pages/mymarket/history.tsx
  src/pages/payments/success.tsx
Labels: feat

#66 [feat] 상품 상세 조회 API 연동
  src/components/items/CartItem.tsx
  src/components/items/CategoryItem.tsx
  src/components/items/HistoryItem.tsx
  src/components/items/MainItem.tsx
  src/components/items/MyDongleHistoryItem.tsx
  src/pages/category/food.tsx
  src/pages/home/index.tsx
  src/pages/item/[id]/index.tsx
  src/services/api/categoryAPI.ts
  src/services/api/itemAPI.ts
  src/services/item/item.ts
  src/services/item/item.type.ts
  src/types/item.ts
  src/utils/itemIdRouting.ts
Labels: feat

#71 [fix] 빌드에러 해결
  src/components/header/CategoryHeader.tsx
  src/components/header/ItemHeader.tsx
  src/components/header/MainHeader.tsx
  src/components/header/Toggle.tsx
  src/components/items/CartItem.tsx
  src/components/items/HistoryItem.tsx
  src/components/items/LogoutModal.tsx
  src/components/items/MyDongleHistoryItem.tsx
  src/components/items/OrderCancelModal.tsx
  src/components/items/OrderSummary.tsx
  src/components/items/PassPort.tsx
  src/components/items/PetsPort.tsx
  src/components/items/SelectPets.tsx
  src/components/main/Banner.tsx
  src/components/navbar/MainFooterNav.tsx
  src/components/payments/NoTossPayButton.tsx
  src/components/payments/OrderItem.tsx
  src/components/payments/TossPayButton.tsx
  src/global.d.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/category/food.tsx
  src/pages/category/goods.tsx
  src/pages/category/index.tsx
  src/pages/category/snack.tsx
  src/pages/home/index.tsx
  src/pages/item/[id]/index.tsx
  src/pages/myDongle/index.tsx
  src/pages/mydongle/add.tsx
  src/pages/mymarket/cart.tsx
  src/pages/mymarket/history.tsx
  src/pages/payments/index.tsx
  src/pages/payments/success.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/services/item/item.ts
  src/services/payments/payments.ts
  src/services/payments/toss.ts
  src/services/pets/pets.ts
  src/services/users/users.ts
Labels: fix

#72 [feat] 마이마켓: 주문내역 조회 API 연동
  src/components/items/HistoryItem.tsx
  src/components/items/SelectPets.tsx
  src/pages/mydongle/add.tsx
  src/pages/mymarket/history.tsx
  src/services/order/order.ts
  src/services/order/order.type.ts
Labels: feat

#75 [feat] 반려동물 수정/삭제 API 연동
  src/components/items/PetsPort.tsx
  src/pages/mydongle/add.tsx
Labels: feat

#77 [hotfix] mydongle 파일 삭제
  src/pages/myDongle/index.tsx
  src/pages/mydongle/add.tsx
Labels: fix

#79 [hotfix] 마이동글 폴더 재 생성
  src/pages/mydongle/add.tsx
  src/pages/mydongle/index.tsx
Labels: fix

#80 [feat] 마이마켓: 주문내역 취소 API 연동
  src/components/items/HistoryItem.tsx
  src/components/items/OrderCancelModal.tsx
  src/pages/mymarket/history.tsx
  src/services/order/order.ts
  src/services/order/order.type.ts
Labels: feat

#83 [feat] 내 정보 조회 API 연동
  src/components/items/PassPort.tsx
  src/pages/profile/edit.tsx
Labels: feat

#85 [feat] 상품 개별 주문
  public/images/skeleton/itempage_skeleton.png
  public/svgs/logo/data_loading_cat.svg
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/common/Fallback.tsx
  src/components/common/Loading.tsx
  src/components/navbar/ItemFooter.tsx
  src/pages/item/[id]/index.tsx
  src/pages/mymarket/cart.tsx
  src/pages/payments/index.tsx
  src/styles/globals.css
Labels: feat

#86 [feat] 위시리시트: 미사용 페이지 대체뷰
  src/components/items/HistoryItem.tsx
  src/pages/mydongle/index.tsx
  src/pages/mymarket/wishlist.tsx
Labels: feat

#88 [feat] 카테고리: 상품 없을 때 컴포넌트
  src/components/common/NoProduct.tsx
  src/pages/mydongle/index.tsx
Labels: feat

#90 [feat] 유저 정보 활용
  package-lock.json
  package.json
  src/components/header/CategoryDetailHeader.tsx
  src/components/header/CategoryHeader.tsx
  src/components/header/ItemHeader.tsx
  src/components/header/PaymentsHeader.tsx
  src/components/navbar/CategoryFooterNav.tsx
  src/components/navbar/MainFooterNav.tsx
  src/components/navbar/MyDongleFooterNav.tsx
  src/components/navbar/MyMarketFooterNav.tsx
  src/components/navbar/UserInfoFooterNav.tsx
  src/pages/category/food.tsx
  src/pages/category/goods.tsx
  src/pages/category/index.tsx
  src/pages/category/snack.tsx
  src/pages/home/index.tsx
  src/pages/item/[id]/index.tsx
  src/pages/mydongle/add.tsx
  src/pages/mydongle/index.tsx
  src/pages/mymarket/cart.tsx
  src/pages/mymarket/history.tsx
  src/pages/mymarket/wishlist.tsx
  src/pages/payments/index.tsx
  src/pages/payments/success.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/services/carts/carts.type.ts
  src/services/users/users.type.ts
  src/store/user.ts
Labels: fix, feat

#92 [feat] 내 정보 수정 API 연동
  public/images/skeleton/userpage_skeleton.png
  src/components/items/PassPort.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/services/users/users.ts
Labels: feat

#95 [feat] 주문완료 페이지 UI/API
  public/svgs/element/rocket_big.svg
  src/components/items/HistoryItem.tsx
  src/components/items/OrderCompleteItem.tsx
  src/pages/mymarket/history.tsx
  src/pages/payments/success.tsx
Labels: feat

#97 [feat] 결제완료: 페이지 레이아웃 수정
  src/pages/payments/success.tsx
Labels: feat

#98 [fix] 상품 상세 페이지 카테고리 라우팅
  src/components/items/CartItem.tsx
  src/components/items/HistoryItem.tsx
  src/components/items/ItemInfo.tsx
  src/components/items/MyDongleHistoryItem.tsx
  src/components/items/OrderCompleteItem.tsx
  src/components/items/SelectPets.tsx
  src/components/navbar/ItemFooter.tsx
  src/components/payments/OrderItem.tsx
  src/pages/item/[id]/index.tsx
  src/pages/mydongle/add.tsx
  src/pages/mydongle/index.tsx
  src/pages/mymarket/cart.tsx
  src/pages/mymarket/history.tsx
  src/pages/payments/success.tsx
  src/types/item.ts
Labels: fix

#102 [hotfix] 상품 쿼리 정리
  src/components/items/CategoryItem.tsx
  src/components/items/MyDongleHistoryItem.tsx
  src/components/items/PetsPort.tsx
  src/pages/category/food.tsx
  src/pages/category/goods.tsx
  src/pages/category/index.tsx
  src/pages/category/snack.tsx
  src/pages/home/index.tsx
  src/pages/mydongle/[id]/index.tsx
  src/pages/mydongle/add.tsx
  src/services/item/item.ts
Labels: fix

#103 [feat] 주문완료 페이지: 디자인 수정
  public/svgs/element/rocket_big.svg
  public/svgs/element/rocket_success.svg
  src/pages/payments/success.tsx
Labels: feat

#106 [fix] 마이동글 반려동물 수정/삭제 점검
  src/components/header/MyDongleHeader.tsx
  src/components/items/HistoryItem.tsx
  src/components/items/PetsPort.tsx
  src/pages/_app.tsx
  src/pages/mydongle/[id]/index.tsx
  src/pages/mydongle/add.tsx
  src/pages/profile/edit.tsx
  src/services/pets/pets.ts
Labels: fix

#104 [feat] 장바구니 api
  src/components/items/CartItem.tsx
  src/components/items/HistoryItem.tsx
  src/components/items/PassPort.tsx
  src/components/navbar/CategoryFooterNav.tsx
  src/components/navbar/ItemFooter.tsx
  src/components/navbar/MainFooterNav.tsx
  src/components/navbar/MyDongleFooterNav.tsx
  src/components/navbar/MyMarketFooterNav.tsx
  src/components/navbar/UserInfoFooterNav.tsx
  src/pages/home/index.tsx
  src/pages/mymarket/cart.tsx
  src/pages/mymarket/history.tsx
  src/pages/payments/success.tsx
  src/services/carts/carts.ts
  src/services/carts/carts.type.ts
  src/services/users/users.type.ts
  src/styles/globals.css
  src/types/item.ts
Labels: feat, refactor

#108 [feat] 주문내역 반려동물 연결
  src/components/items/CategoryItem.tsx
  src/components/items/HistoryItem.tsx
  src/components/items/MyDongleHistoryItem.tsx
  src/components/items/PetsPort.tsx
  src/components/items/SelectPets.tsx
  src/components/items/WishSelectPets.tsx
  src/pages/mydongle/[id]/index.tsx
  src/pages/mydongle/add.tsx
  src/pages/mymarket/cart.tsx
  src/pages/mymarket/history.tsx
  src/pages/payments/success.tsx
  src/services/order/order.ts
  src/services/order/order.type.ts
  src/services/pets/pets.type.ts
  src/utils/formatDeliveryDate.ts
Labels: feat, refactor

#110 [feat] 로딩 페이지
  public/images/skeleton/cartpage_skeleton.png
  public/images/skeleton/mainpage_skeleton.png
  public/images/skeleton/petpage_skeleton.png
  src/components/common/Loading.tsx
  src/components/items/PassPort.tsx
  src/pages/category/food.tsx
  src/pages/category/goods.tsx
  src/pages/category/snack.tsx
  src/pages/home/index.tsx
  src/pages/item/[id]/index.tsx
  src/pages/mydongle/[id]/index.tsx
  src/pages/mymarket/cart.tsx
  src/pages/mymarket/history.tsx
  src/pages/profile/edit.tsx
Labels: feat
