Repository Dongle-market/Dongle-FE, pull requests merged in 2024-10, with the labels that each got.

#2 chore: FrontEnd 레포 설정 수정
  next.config.mjs
  package-lock.json
  package.json
  public/svgs/basket.svg
  public/svgs/dog.svg
  public/svgs/dogfoot.svg
  public/svgs/dongle.svg
  public/svgs/hamburger.svg
  public/svgs/my.svg
  public/svgs/shopping_basket.svg
  public/svgs/whitedog.svg
  src/app/fonts/PretendardVariable.woff2
  src/app/globals.css
  src/app/page.tsx
  src/app/test/page.tsx
  src/components/layout/FooterNav.tsx
  src/components/layout/MainHeader.tsx
Labels: chore

#7 [feat] 카테고리 레이아웃 구현
  src/app/category/page.tsx
  src/app/globals.css
  src/components/layout/CategoryFooterNav.tsx
  src/components/layout/CategoryHeader.tsx
  src/components/layout/MainFooterNav.tsx
  src/components/layout/MainHeader.tsx
  src/components/layout/MyDongleFooterNav.tsx
  src/components/layout/MyMarketFooterNav.tsx
  src/components/layout/UserInfoFooterNav.tsx
Labels: feat

#8 [feat] 메인페이지 레이아웃 구현
  package-lock.json
  package.json
  public/images/background_main.png
  public/images/banner1.png
  public/images/banner2.png
  public/images/banner3.png
  public/images/product1.png
  src/app/dog/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/Banner.tsx
  src/components/MainItem.tsx
  src/components/MenuBar.tsx
  src/components/Toggle.tsx
  src/components/layout/MainFooterNav.tsx
  src/components/layout/MainHeader.tsx
Labels: feat

#15 [hotfix] page router 다운그레이드
  public/PretendardVariable.woff2
  public/favicon.ico
  src/app/StyledComponentsRegistry.tsx
  src/app/layout.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/category/index.tsx
  src/pages/dog/index.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: fix

#16 Feat#5 카테고리 상품리스트 레이아웃 구현
  public/svgs/element/down_arrow.svg
  public/svgs/element/heart.svg
  public/svgs/element/heart_full.svg
  src/components/header/CategoryDetailHeader.tsx
  src/components/header/SelectBox.tsx
  src/components/items/CategoryItem.tsx
  src/components/items/CategoryItemsRow.tsx
  src/pages/category/food.tsx
  src/pages/category/goods.tsx
  src/pages/category/snack.tsx
Labels: feat

#17 [feat] 마이마켓 위시리스트 레이아웃 구현
  Icon 
  public/images/CatEmoji.png
  public/images/DogEmoji.png
  public/images/RabbitEmoji.png
  public/images/banner1.png
  public/images/banner2.png
  public/images/banner3.png
  public/svgs/element/An.svg
  public/svgs/element/Baek.svg
  src/components/header/CategoryHeader.tsx
  src/components/header/TabMenu.tsx
  src/components/items/CategoryItem.tsx
  src/components/items/CategoryItemsRow.tsx
  src/components/items/MainItem.tsx
  src/components/items/SelectPets.tsx
  src/components/main/Banner.tsx
  src/components/navbar/MainFooterNav.tsx
  src/components/navbar/MyMarketFooterNav.tsx
  src/pages/dog/index.tsx
  src/pages/mymarket/wishlist.tsx
Labels: feat

#21 Fix#20 카테고리 상품 상세 리스트 픽스
  src/components/header/CategoryDetailHeader.tsx
  src/components/header/SelectBox.tsx
  src/components/navbar/CategoryFooterNav.tsx
  src/pages/category/food.tsx
  src/pages/category/goods.tsx
  src/pages/category/index.tsx
  src/pages/category/snack.tsx
Labels: fix

#19 Feat#12 상품 상세조회 레이아웃 구현
  package-lock.json
  package.json
  public/images/catdongle.jpeg
  public/images/gom.jpeg
  public/images/soogom.jpeg
  public/svgs/element/forward_arrow.svg
  public/svgs/element/minus.svg
  public/svgs/element/plus.svg
  src/components/header/ItemHeader.tsx
  src/components/items/ItemInfo.tsx
  src/components/navbar/ItemFooter.tsx
  src/pages/item/index.tsx
Labels: feat

#24 [feat] 마이마켓 주문내역 레이아웃 구현
  src/components/header/CategoryDetailHeader.tsx
  src/components/header/CategoryHeader.tsx
  src/components/header/MainHeader.tsx
  src/components/items/HistoryItem.tsx
  src/components/navbar/CategoryFooterNav.tsx
  src/components/navbar/ItemFooter.tsx
  src/components/navbar/MainFooterNav.tsx
  src/components/navbar/MyMarketFooterNav.tsx
  src/pages/home/index.tsx
  src/pages/mymarket/cart.tsx
  src/pages/mymarket/history.tsx
  src/pages/mymarket/wishlist.tsx
Labels: feat

#28 [feat] 메인 헤더 디자인 수정
  public/svgs/element/box.svg
  public/svgs/element/check.svg
  public/svgs/element/check_box.svg
  public/svgs/element/down_arrow.svg
  public/svgs/element/non_check.svg
  public/svgs/element/toss_pay_logo.svg
  src/components/header/CategoryHeader.tsx
  src/components/header/MainHeader.tsx
  src/components/header/MenuBar.tsx
  src/components/header/Toggle.tsx
  src/components/items/CartItem.tsx
  src/components/items/MainItem.tsx
  src/components/main/Banner.tsx
  src/pages/home/index.tsx
  src/pages/mymarket/cart.tsx
Labels: feat

#29 [Feat] 카카오 로그인
  public/svgs/element/kakao_login.svg
  public/svgs/element/kakao_logo.svg
  public/svgs/logo/biglogo_dongle_eng.svg
  public/svgs/logo/biglogo_dongle_kor.svg
  public/svgs/logo/loading_cat.svg
  src/components/login/KakaoLoginButton.tsx
  src/components/login/LoginComponent.tsx
  src/components/login/SplashComponent.tsx
  src/pages/_app.tsx
  src/pages/auth/callback.tsx
  src/pages/index.tsx
  src/services/auth/auth.ts
  src/services/auth/auth.types.ts
  src/services/auth/index.ts
  src/services/auth/kakao.ts
  src/services/axios.setting.ts
  src/utils/detectDevice.ts
Labels: feat

#30 [feat] 결제 페이지 레이아웃 구현
  public/svgs/element/arrow_down.svg
  public/svgs/element/arrow_up.svg
  src/components/header/PaymentsHeader.tsx
  src/components/items/CartItem.tsx
  src/components/items/OrderSummary.tsx
  src/components/payments/NoTossPayButton.tsx
  src/components/payments/OrderItem.tsx
  src/components/payments/TossPayButton.tsx
  src/components/payments/UserContactInfo.tsx
  src/pages/item/payments.tsx
  src/pages/mydongle/add.tsx
  src/pages/mymarket/cart.tsx
Labels: feat
